stages:
  - test
  - coverage
  - lint

variables:
  PYTHON_VERSION: "3.8"

default:
  image: python:$PYTHON_VERSION

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - pytest

coverage:
  stage: coverage
  script:
    - pip install -r requirements.txt
    - pip install pytest coverage pytest-cov
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - pytest --cov=uav_control --cov-report=xml
  artifacts:
    reports:
      cobertura: coverage.xml

lint:
  stage: lint
  script:
    - pip install pylint
    - pylint uav_control.py
